
services:
  app:
    build: .
    container_name: go_app
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdbname
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

