
services:
  app:
    build: .
    container_name: go_app
    environment:
      -DB="host=localhost user=postgres password=new_password dbname=library port=5432 sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdbname
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

